# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.define "soloc" do |soloc|
    soloc.vm.box = "ubuntu/trusty64"
    soloc.vm.host_name = "soloc"
    soloc.vm.network :private_network, ip: "192.168.56.104"
    soloc.vm.network "public_network", :bridge => 'en0: Ethernet'
    config.vm.provision "chef_solo" do |chef|
      git "#{Chef::Config[:file_cache_path]}/apache2-c" do
        repository "git://github.com:viverae-cookbooks/apache2.git"
        action :sync
      end
      chef.add_recipe "emacs"
    end
  end
end
